apiVersion: v1
kind: Pod
metadata:
  name: privileged-app
  labels:
    app: privileged-app
  namespace: demo
spec:
  containers: 
  - image: busybox 
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: priv-container 
    securityContext:
      privileged: true
#      allowPrivilegeEscalation: false
#      runAsUser: 0
#    restartPolicy: Always

