apiVersion: v1
kind: Pod
metadata:
  name: vanila-ubuntu 
  labels:
    app: vanila-ubuntu
  namespace: demo
spec:
  containers: 
  - image:  ubuntu
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name:  just-ubuntu

